package commanLib.Registration;

import commanLib.CATFeedback.*;
import java.awt.Color;
import javax.swing.JOptionPane;

public class Dialog_RegSendSave extends javax.swing.JDialog 
{
    private final String FROM;       
    private final String SUBJECT;
    private final String MESSAGE_BODY;   
    private final Registration REG;
    
    private final String SEND_MSG_1 = "Registration Successfully Completed!"+"\n"+
                                    "Thank you for taking out some of your time and providing us"+"\n"+ 
                                    "with your details. You are now good to go, to use this software."+"\n"+
                                    "A registration email has been send to the support team. You can"+"\n"+
                                    "find a copy of this email in the ‘Send Mail’ option of your email id."+"\n"+
                                    "In order to complete the process, we recommend you to kindly"+"\n"+
                                    "click ‘OK’ and restart the application manually.";
    
    public Dialog_RegSendSave(java.awt.Frame parent, boolean modal,String FROM,Registration REG) 
    {
        super(parent, modal);
        
        this.FROM=FROM;
        this.REG=REG;
        
        this.SUBJECT="CAT Registration ("+REG.firstName+" "+REG.lastName+" | "+REG.phoneNo+")";
                
        this.MESSAGE_BODY="Support Team"+"\n"+
                        "Compiler Automation Tool (CAT)"+"\n\n"+
                        "I "+REG.firstName+" "+REG.lastName+" register myself with following details to the support team of Compiler Automation Tool to kindly allow me to use this software."+"\n\n"+
                        REG.toString()+"\n\n"+
                        "User Agreements:"+"\n"+
                        "I hereby accept the following terms and conditions imposed by the support team on me to use this software:"+"\n"+
                        "   •	I am a genuine owner of this product."+"\n"+
                        "   •	All information stated above are true to the best of my knowledge."+"\n"+
                        "   •	I shall not try to decompile any part of this software using unfair means.";
        
        initComponents();        
        //progBar.setVisible(false);
        popup_MoreInfo.add(scrollPn_textA_moreInfo);        
        
        this.setLocationRelativeTo(null);      
        
        textF_email.setText(FROM);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popup_MoreInfo = new javax.swing.JPopupMenu();
        scrollPn_textA_moreInfo = new javax.swing.JScrollPane();
        textA_moreInfo = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textF_email = new javax.swing.JTextField();
        passF_pass = new javax.swing.JPasswordField();
        btn_send = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();
        textA_SerialMsg = new javax.swing.JTextArea();
        btn_moreInfo = new javax.swing.JButton();

        popup_MoreInfo.setMaximumSize(new java.awt.Dimension(435, 284));
        popup_MoreInfo.setMinimumSize(new java.awt.Dimension(435, 284));
        popup_MoreInfo.setPreferredSize(new java.awt.Dimension(435, 284));

        textA_moreInfo.setEditable(false);
        textA_moreInfo.setColumns(20);
        textA_moreInfo.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_moreInfo.setLineWrap(true);
        textA_moreInfo.setRows(5);
        textA_moreInfo.setText("This is the final step of the registration where you must authenticate yourself via your email id. This step is mandatory to make sure you are not only the genuine user but also you are using original product. All the details you have entered in previous step are required to be mailed to the support team from your email id. In order to reduce user efforts and time, this process has been automated with this registration process, so you need not explicitly compose a mail that too in unformatted form. As you enter your details and authenticate yourself through your email id and password, a mail will be automatically composed from your email with all the summary of details entered by you in a formatted form and send to us on the following mail: singh.gagan144@gmail.com. Moreover, you may find the copy of this mail in your ‘Send Mail’ option of your account.\n\nHere we would like to say and guarantee that your PASSWORD WILL REMAIN YOUR CONFIDENTIAL ASSET AND WILL NOT BE EXPOSED TO US OR ANYONE ELSE IN ANY FORM. You may cross check this by viewing a copy of this mail from your ‘Send Mail’ option. \n\nIf you still feel insecure, you must know that this mailing process has been accomplished using JavaMail API 1.4.7 Library. You may go through the documentation of JavaMail API 1.4.7 by surfing on internet or visit the link http://www.oracle.com/technetwork/java/index-138643.html. \n\nPlease feel free to authenticate yourself as we guarantee that your password will always remain your personal confidential asset. \n\nRegards\nSupport Team\nsingh.gagan144@gmail.com");
        textA_moreInfo.setWrapStyleWord(true);
        scrollPn_textA_moreInfo.setViewportView(textA_moreInfo);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Email Authentication");
        setLocationByPlatform(true);
        setMaximumSize(new java.awt.Dimension(363, 235));
        setMinimumSize(new java.awt.Dimension(363, 235));
        setPreferredSize(new java.awt.Dimension(363, 235));
        setResizable(false);

        jLabel2.setText("Email Id :");

        jLabel3.setText("Password :");

        textF_email.setEditable(false);

        passF_pass.setToolTipText("Your email id passwaord");

        btn_send.setText("Register");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_cancel.setText("Cancel");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        textA_SerialMsg.setEditable(false);
        textA_SerialMsg.setColumns(20);
        textA_SerialMsg.setFont(new java.awt.Font("Tahoma", 0, 11)); // NOI18N
        textA_SerialMsg.setLineWrap(true);
        textA_SerialMsg.setRows(5);
        textA_SerialMsg.setText("In order to complete the registration, you must send your details to the support team. To do so, please authenticate your email id by entering your password. On completion, a registration email will be automatically generated and send via your email.");
        textA_SerialMsg.setWrapStyleWord(true);
        textA_SerialMsg.setOpaque(false);

        btn_moreInfo.setForeground(new java.awt.Color(0, 51, 255));
        btn_moreInfo.setText("Click here to know more about authentication...");
        btn_moreInfo.setBorderPainted(false);
        btn_moreInfo.setContentAreaFilled(false);
        btn_moreInfo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_moreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_moreInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(textA_SerialMsg)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textF_email)
                            .addComponent(passF_pass)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_moreInfo)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(textA_SerialMsg, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_moreInfo, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passF_pass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:        
        String from=null,pass=null;
        
        if(passF_pass.getText().equals(""))
        { passF_pass.setBackground(new Color(255,185,185));  
          return; 
        }
        from=FROM;
        pass=passF_pass.getText();
                        
        
        EmailHandler email = new EmailHandler(from, pass, SUBJECT, MESSAGE_BODY);        
        try
        {
            //progBar.setVisible(true);
            //(A) Save on machine
            REG.writeRegFile();
            
            try
            {
                //(B) send email
                email.sendMail();
                
                dispose();
                JOptionPane.showMessageDialog(this, SEND_MSG_1,"Registration Successfully Completed!", JOptionPane.INFORMATION_MESSAGE);                              
                System.exit(0);
            }catch(Exception ex)
            { 
                //progBar.setVisible(false);
                String msg="",title="";
                try{
                    //delete registration file
                    Registration.deleteRegFile();
                    
                    //set msg
                    int expNo=Integer.parseInt(ex.getMessage());
                    switch(expNo)
                    {
                        case EmailHandler.AUTH_EXCPTN : 
                             {
                                 title="Authentication Error!";
                                 msg="Please verify your Email Id and Password.\nMake sure you are using a valid Gmail Id!";
                             }break;
                        case EmailHandler.CONNECT_EXCPTN :
                             {
                                 title="Internet Connectivity Error!";
                                 msg="Please make sure you are connected to internet.\nCheck your modem sockets or internet\nconnection settings and try again!";
                             }break;
                    }
                }catch(Exception e)
                {
                    title="Error Sending Mail!";
                    msg="An error occured sending email.\nPlease try again later!";
                }
            
                JOptionPane.showMessageDialog(this, msg, title, JOptionPane.ERROR_MESSAGE);
                //e.printStackTrace();             
                //Dialog_ExceptionHandler.autoPopJOptionPane(this, "Error Sending Message...", e.getMessage(), e, JOptionPane.ERROR_MESSAGE);            
            }
            
        }
        catch(Throwable t) //catch(Exception e)
        {
            System.out.println("ERROR : "+t.getMessage());
                JOptionPane.showMessageDialog(this,
                    "An error occurred while saving your registration!"+"\n"+
                    "Please make sure you are logged in as an administrator"+"\n"+
                    "and the installation directory is writable!",
                    
                    "Error Saving Registration...", 
                    JOptionPane.ERROR_MESSAGE
                );            
        }
        
        
    }//GEN-LAST:event_btn_sendActionPerformed

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void btn_moreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_moreInfoActionPerformed
        // TODO add your handling code here:
        if(!popup_MoreInfo.isShowing())
        {
            popup_MoreInfo.show(this, btn_moreInfo.getLocation().x, btn_moreInfo.getLocation().y);
        }
    }//GEN-LAST:event_btn_moreInfoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_SendMail.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Dialog_RegSendSave dialog = new Dialog_RegSendSave(new javax.swing.JFrame(),true,null,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_moreInfo;
    private javax.swing.JButton btn_send;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPasswordField passF_pass;
    private javax.swing.JPopupMenu popup_MoreInfo;
    private javax.swing.JScrollPane scrollPn_textA_moreInfo;
    private javax.swing.JTextArea textA_SerialMsg;
    private javax.swing.JTextArea textA_moreInfo;
    private javax.swing.JTextField textF_email;
    // End of variables declaration//GEN-END:variables
}
