package editor;

import com.mxgraph.swing.mxGraphComponent;
import commanLib.DfaFunctions;
import commanLib.DtransNode;
import commanLib.GlobalFunctions;
import commanLib.GraphNode;
import commanLib.Panel_Trans_legends;
import commanLib.Panel_mxGraphDisplay;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

public class DfaPanel extends javax.swing.JPanel 
{
    private Panel_mxGraphDisplay panel_mxGraph=null;

    public DfaPanel() {
        initComponents();
        
        //scrollpane corner button
        //scrollPane_mxGraph.setCorner(JScrollPane.LOWER_RIGHT_CORNER, tglBtn_outline);
        
        //popup menu
        popMenu_legends.add(new Panel_Trans_legends());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tglBtn_outline = new javax.swing.JToggleButton();
        popMenu_outline = new javax.swing.JPopupMenu();
        popMenu_legends = new javax.swing.JPopupMenu();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        DtransTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btn_mxGraph_fit = new javax.swing.JButton();
        btn_mxGraph_zoomOut = new javax.swing.JButton();
        btn_mxGraph_zoomIn = new javax.swing.JButton();
        btn_mxGraph_autoLayt = new javax.swing.JButton();
        tglBtn_legends = new javax.swing.JToggleButton();
        panel = new javax.swing.JPanel();

        tglBtn_outline.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/eye.png"))); // NOI18N
        tglBtn_outline.setToolTipText("Adjust View");
        tglBtn_outline.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        tglBtn_outline.setFocusPainted(false);
        tglBtn_outline.setFocusable(false);
        tglBtn_outline.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtn_outlineActionPerformed(evt);
            }
        });

        popMenu_outline.setMaximumSize(new java.awt.Dimension(101, 101));
        popMenu_outline.setMinimumSize(new java.awt.Dimension(101, 101));
        popMenu_outline.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                popMenu_outlinePopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        popMenu_legends.setMaximumSize(new java.awt.Dimension(141, 101));
        popMenu_legends.setMinimumSize(new java.awt.Dimension(141, 101));
        popMenu_legends.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                popMenu_legendsPopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });

        setBackground(new java.awt.Color(255, 255, 255));
        setOpaque(false);
        setPreferredSize(new java.awt.Dimension(500, 400));

        jSplitPane1.setDividerLocation(140);
        jSplitPane1.setOrientation(javax.swing.JSplitPane.VERTICAL_SPLIT);
        jSplitPane1.setOneTouchExpandable(true);
        jSplitPane1.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                jSplitPane1PropertyChange(evt);
            }
        });

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dtrans Table", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        DtransTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DtransTable.setEditingColumn(1);
        DtransTable.setRowSelectionAllowed(false);
        DtransTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DtransTable);

        jSplitPane1.setTopComponent(jScrollPane1);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "DFA", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        btn_mxGraph_fit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/Images/zoomFit.png"))); // NOI18N
        btn_mxGraph_fit.setText("Fit on Screen");
        btn_mxGraph_fit.setToolTipText("Fit on Screen");
        btn_mxGraph_fit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mxGraph_fit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mxGraph_fitActionPerformed(evt);
            }
        });

        btn_mxGraph_zoomOut.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/Images/zoomOut.png"))); // NOI18N
        btn_mxGraph_zoomOut.setToolTipText("Zoom Out");
        btn_mxGraph_zoomOut.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mxGraph_zoomOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mxGraph_zoomOutActionPerformed(evt);
            }
        });

        btn_mxGraph_zoomIn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/editor/Images/zoomIn.png"))); // NOI18N
        btn_mxGraph_zoomIn.setToolTipText("Zoom In");
        btn_mxGraph_zoomIn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mxGraph_zoomIn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mxGraph_zoomInActionPerformed(evt);
            }
        });

        btn_mxGraph_autoLayt.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/autoLayout.png"))); // NOI18N
        btn_mxGraph_autoLayt.setText("Auto Layout");
        btn_mxGraph_autoLayt.setToolTipText("Automatically set layout");
        btn_mxGraph_autoLayt.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btn_mxGraph_autoLayt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_mxGraph_autoLaytActionPerformed(evt);
            }
        });

        tglBtn_legends.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        tglBtn_legends.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/legends.png"))); // NOI18N
        tglBtn_legends.setText("Legends");
        tglBtn_legends.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        tglBtn_legends.setContentAreaFilled(false);
        tglBtn_legends.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tglBtn_legends.setPreferredSize(new java.awt.Dimension(70, 23));
        tglBtn_legends.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tglBtn_legendsActionPerformed(evt);
            }
        });

        panel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panel.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentResized(java.awt.event.ComponentEvent evt) {
                panelComponentResized(evt);
            }
        });

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 194, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(btn_mxGraph_zoomIn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mxGraph_zoomOut, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mxGraph_fit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_mxGraph_autoLayt)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                        .addComponent(tglBtn_legends, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(panel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_mxGraph_zoomIn, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_mxGraph_zoomOut, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btn_mxGraph_autoLayt)
                            .addComponent(tglBtn_legends, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(btn_mxGraph_fit))))
        );

        jSplitPane1.setRightComponent(jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_mxGraph_fitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mxGraph_fitActionPerformed
        // TODO add your handling code here:
        if(panel_mxGraph!=null)
        panel_mxGraph.zoomToFit(panel.getSize());
    }//GEN-LAST:event_btn_mxGraph_fitActionPerformed

    private void btn_mxGraph_zoomOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mxGraph_zoomOutActionPerformed
        // TODO add your handling code here:
        if(panel_mxGraph!=null)
        panel_mxGraph.zoomOut();
    }//GEN-LAST:event_btn_mxGraph_zoomOutActionPerformed

    private void btn_mxGraph_zoomInActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mxGraph_zoomInActionPerformed
        // TODO add your handling code here:
        if(panel_mxGraph!=null)
        panel_mxGraph.zoomIn();
    }//GEN-LAST:event_btn_mxGraph_zoomInActionPerformed

    private void tglBtn_outlineActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtn_outlineActionPerformed
        // TODO add your handling code here:

        if(!popMenu_outline.isShowing() && tglBtn_outline.isSelected())
        {
            //System.out.println("SHOW");
            int x=tglBtn_outline.getX();
            int y=tglBtn_outline.getY();

            x=x-68;
            y=y+64;
            popMenu_outline.show(this, x,y);
        }
        else
        { tglBtn_outline.setSelected(false); }
    }//GEN-LAST:event_tglBtn_outlineActionPerformed

    private void popMenu_outlinePopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_popMenu_outlinePopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        tglBtn_outline.setSelected(false);
    }//GEN-LAST:event_popMenu_outlinePopupMenuWillBecomeInvisible

    private void popMenu_legendsPopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_popMenu_legendsPopupMenuWillBecomeInvisible
        // TODO add your handling code here:
        tglBtn_legends.setSelected(false);
    }//GEN-LAST:event_popMenu_legendsPopupMenuWillBecomeInvisible

    private void btn_mxGraph_autoLaytActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_mxGraph_autoLaytActionPerformed
        // TODO add your handling code here:
        if(panel_mxGraph!=null)
        panel_mxGraph.autolayout();
    }//GEN-LAST:event_btn_mxGraph_autoLaytActionPerformed

    private void tglBtn_legendsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tglBtn_legendsActionPerformed
        // TODO add your handling code here:
        if(!popMenu_legends.isShowing() && tglBtn_legends.isSelected())
        {
            int x=tglBtn_legends.getX();
            int y=tglBtn_legends.getY();

            x=x-72;
            y=y+43;
            popMenu_legends.show(this, x,y);
        }
        else
        { tglBtn_legends.setSelected(false); }
    }//GEN-LAST:event_tglBtn_legendsActionPerformed

    private void panelComponentResized(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_panelComponentResized
        // TODO add your handling code here:
        if(panel_mxGraph!=null)
        { panel_mxGraph.adjustSizeOfGraphComp(panel.getSize()); }
    }//GEN-LAST:event_panelComponentResized

    private void jSplitPane1PropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_jSplitPane1PropertyChange
        // TODO add your handling code here:
        if(panel_mxGraph!=null)
        { panel_mxGraph.adjustSizeOfGraphComp(panel.getSize()); }
        //System.out.println("Divider moved!");
    }//GEN-LAST:event_jSplitPane1PropertyChange

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable DtransTable;
    private javax.swing.JButton btn_mxGraph_autoLayt;
    private javax.swing.JButton btn_mxGraph_fit;
    private javax.swing.JButton btn_mxGraph_zoomIn;
    private javax.swing.JButton btn_mxGraph_zoomOut;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JPanel panel;
    private javax.swing.JPopupMenu popMenu_legends;
    private javax.swing.JPopupMenu popMenu_outline;
    private javax.swing.JToggleButton tglBtn_legends;
    private javax.swing.JToggleButton tglBtn_outline;
    // End of variables declaration//GEN-END:variables

    //My functions-----------
    
    private void resetTable()
    {
        DtransTable = new javax.swing.JTable();
        
        DtransTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        DtransTable.setEditingColumn(1);
        DtransTable.setRowSelectionAllowed(false);
        DtransTable.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(DtransTable);
    }
    
    public void drawDFA(DtransNode dTrans)
    {
        /*
        //Part of NFAPAnel 
        GraphNode NFA=null,ptr=null;
        NFA=GlobalFunctions.generateNFA(r);     
        
        //reset state name
        ptr=NFA;
        int lbCntr=0;
        while(ptr!=null)
        {
            ptr.lb=String.valueOf(lbCntr++);
            ptr=ptr.nextSt;
        }
        //-----------------------------------
        */
        
        resetTable();
        
        //GraphNode DFA=null;
        DtransNode ptrDtrans=null;
        
        //dTrans= DfaFunctions.genDFAfromNFA(NFA);        
        //DFA=DtransNode.DtransToGraphNode(DFA, dTrans);
        
        int col=0;
        DefaultTableModel model=(DefaultTableModel)DtransTable.getModel();
        
        Character in[]=null;
        
        try
        {
            in=DfaFunctions.retInputArr();            
            
            //set input colms           
            model.addColumn("DFA State");
            model.addColumn("NFA StateSet");
            col=2;
            
            for(int i=0;i<in.length;i++)
            {
                model.addColumn("Input '"+in[i]+"'");
                col++;                
            }
            
            DtransTable = new JTable(model) ;
           
        }catch(Exception e)
        { System.out.println("DfaPanel | "+e); }
        
                
        //set Data  to table
        ptrDtrans=dTrans;
        
        Object data[];
        
        while(ptrDtrans!=null)
        {        
            data=ptrDtrans.createTableRow(col,in);
            
            model.insertRow(DtransTable.getRowCount(), data);
            ptrDtrans=ptrDtrans.nextSET;
        }
        
        
    }
    
    public void displayDFAGraph(GraphNode dfa) throws Exception
    {
        //display mxGraph
        //try
        //{           
            panel.removeAll();
            
            panel_mxGraph = new Panel_mxGraphDisplay(DfaFunctions.createMxGraph(dfa));
            //scrollPane_mxGraph.setViewportView(panel_mxGraph); 
            panel_mxGraph.setSize(panel.getSize());
        
            mxGraphComponent graphCmp=panel_mxGraph.getMxGraphComponent();
            graphCmp.setSize(panel.getSize());        
            graphCmp.setCorner(JScrollPane.LOWER_RIGHT_CORNER, tglBtn_outline);
            panel.add(graphCmp);
            panel.paintComponents(panel.getGraphics());    
            
            //outline popUP menu
            popMenu_outline.removeAll();
            popMenu_outline.add(panel_mxGraph.getGraphOutline());
            
        //}catch(Exception e)
        //{ LanguageEditor.setMessages("| DFA - Unable to display graph! ", "", 100); }
    }
    
    public void resizeGraphPanel()
    {
        if(panel_mxGraph!=null)
        { panel_mxGraph.adjustSizeOfGraphComp(panel.getSize()); }
    }
    
}
