/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package Test;

import javax.swing.DefaultCellEditor;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;

/**
 *
 * @author Gagandeep
 */
public class ComboBoxInTable extends javax.swing.JFrame {

    /**
     * Creates new form ComboBoxInTable
     */
    public ComboBoxInTable() {
        
         try{
              UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
          }catch(Exception e)
          {  System.out.println("Windows isn't available"); }
         
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Links = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_Links = new javax.swing.JTable();
        btn_AddTb = new javax.swing.JButton();
        btn_DelTb = new javax.swing.JButton();
        btn_UpTb = new javax.swing.JButton();
        btn_DownTb = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panel_Links.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Links", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        table_Links.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Input", "Next State"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        table_Links.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        table_Links.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table_Links);

        btn_AddTb.setText("+");
        btn_AddTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_AddTbActionPerformed(evt);
            }
        });

        btn_DelTb.setText("-");
        btn_DelTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DelTbActionPerformed(evt);
            }
        });

        btn_UpTb.setText("Up");
        btn_UpTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_UpTbActionPerformed(evt);
            }
        });

        btn_DownTb.setText("Down");
        btn_DownTb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_DownTbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_LinksLayout = new javax.swing.GroupLayout(panel_Links);
        panel_Links.setLayout(panel_LinksLayout);
        panel_LinksLayout.setHorizontalGroup(
            panel_LinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LinksLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_LinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(panel_LinksLayout.createSequentialGroup()
                        .addComponent(btn_AddTb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DelTb, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 166, Short.MAX_VALUE)
                        .addComponent(btn_UpTb)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btn_DownTb)))
                .addContainerGap())
        );
        panel_LinksLayout.setVerticalGroup(
            panel_LinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_LinksLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 310, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_LinksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_AddTb)
                    .addComponent(btn_DelTb)
                    .addComponent(btn_UpTb)
                    .addComponent(btn_DownTb, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(4, 4, 4))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Links, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panel_Links, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_AddTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_AddTbActionPerformed
        // TODO add your handling code here:
        String boxVal[]={"0","1","2","3"};
        JComboBox comboBx = new JComboBox(boxVal);
        
        DefaultTableModel model = (DefaultTableModel) table_Links.getModel();        
        model.insertRow(table_Links.getRowCount(), new Object[]{"",""});
        
        TableColumn stCol = table_Links.getColumnModel().getColumn(1);
        stCol.setCellEditor(new DefaultCellEditor(comboBx));
        
        //count++;
        //textF_cnt.setText(String.valueOf(count));
    }//GEN-LAST:event_btn_AddTbActionPerformed

    private void btn_DelTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DelTbActionPerformed
        // TODO add your handling code here:
        int row = table_Links.getSelectedRow();

        DefaultTableModel model = (DefaultTableModel) table_Links.getModel();
        if (row != -1) {
            model.removeRow(row);
            //count--;
            //textF_cnt.setText(String.valueOf(count));
        }
    }//GEN-LAST:event_btn_DelTbActionPerformed

    private void btn_UpTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_UpTbActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_Links.getModel();
        try {
            int rowCurr = table_Links.getSelectedRow();

            if (rowCurr != 0) {
                model.moveRow(rowCurr, rowCurr, rowCurr - 1);
                table_Links.setRowSelectionInterval(rowCurr - 1, rowCurr - 1);
            }
        } catch (Exception e) {
        }


    }//GEN-LAST:event_btn_UpTbActionPerformed

    private void btn_DownTbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_DownTbActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) table_Links.getModel();
        int rowCurr = table_Links.getSelectedRow();

        if (rowCurr != table_Links.getRowCount() - 1) {
            model.moveRow(rowCurr, rowCurr, rowCurr + 1);
            table_Links.setRowSelectionInterval(rowCurr + 1, rowCurr + 1);
        }
    }//GEN-LAST:event_btn_DownTbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ComboBoxInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ComboBoxInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ComboBoxInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ComboBoxInTable.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new ComboBoxInTable().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_AddTb;
    private javax.swing.JButton btn_DelTb;
    private javax.swing.JButton btn_DownTb;
    private javax.swing.JButton btn_UpTb;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel_Links;
    private javax.swing.JTable table_Links;
    // End of variables declaration//GEN-END:variables
}
