package Compiler;

import commanLib.SystemProperties;
import commanLib.Panel_CpuUsageBar;
import java.util.logging.Level;
import java.util.logging.Logger;

public class Dialog_SystemInfo extends javax.swing.JDialog 
{
    private SystemProperties sysProp=null;
    private RepaintThread repntThrd=null;

    public Dialog_SystemInfo(java.awt.Frame parent, boolean modal,SystemProperties systemProp) 
    {
        super(parent, modal);
        initComponents();
        this.setLocationRelativeTo(null);
        
        if(systemProp!=null)        
        { sysProp=systemProp; }
        else
        { sysProp = new SystemProperties();  }
       
       //Display on table
       table.getModel().setValueAt(sysProp.USER_NAME, 0, 1);
       table.getModel().setValueAt(sysProp.COMPUTER_NAME,1 , 1);
       table.getModel().setValueAt(sysProp.OS_NAME,2 , 1);
       table.getModel().setValueAt(sysProp.OS_VER, 3, 1);
       table.getModel().setValueAt(sysProp.SYS_MANUF, 4, 1);
       table.getModel().setValueAt(sysProp.SYS_MODEL, 5, 1);
       table.getModel().setValueAt(sysProp.SYS_TYPE,6 , 1);
       table.getModel().setValueAt(sysProp.CPU_MODEL,7 , 1);
       table.getModel().setValueAt(sysProp.CPU_SPEED+" MHz",8 , 1);
       table.getModel().setValueAt(sysProp.CPU_CORES,9 , 1);
       table.getModel().setValueAt(sysProp.CPU_MANUF,10 , 1);
       table.getModel().setValueAt(sysProp.RAM,11 , 1);
       
       repntThrd=new RepaintThread();
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        btn_ok = new javax.swing.JButton();
        panel_RamUsageBar = new commanLib.Panel_RamUsageBar();
        panel_CpuUsageBar = new commanLib.Panel_CpuUsageBar();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("System Information");
        setResizable(false);

        jScrollPane1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "System Information", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"User Name", null},
                {"Computer Name", null},
                {"OS Name", null},
                {"OS Version", null},
                {"System Manufacturer", null},
                {"System Model", null},
                {"System Type", null},
                {"CPU Model", null},
                {"CPU Speed", null},
                {"Total CPU Cores", null},
                {"CPU Manufacturer", null},
                {"RAM", null}
            },
            new String [] {
                "System Attribute", "Value"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table.setRowHeight(17);
        table.setShowHorizontalLines(false);
        table.setShowVerticalLines(false);
        table.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(table);
        table.getColumnModel().getColumn(0).setMinWidth(50);
        table.getColumnModel().getColumn(0).setPreferredWidth(120);
        table.getColumnModel().getColumn(0).setMaxWidth(120);

        btn_ok.setText("OK");
        btn_ok.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_okActionPerformed(evt);
            }
        });

        panel_RamUsageBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ram Usage", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N
        panel_RamUsageBar.setToolTipText("Memory Usage");

        panel_CpuUsageBar.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "CPU Usage", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_ok, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(panel_RamUsageBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(panel_CpuUsageBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_RamUsageBar, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                    .addComponent(panel_CpuUsageBar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_ok)
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_okActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_okActionPerformed
        // TODO add your handling code here:
        panel_CpuUsageBar.stopThread();
        panel_RamUsageBar.stopThread();   
        repntThrd.stop();
        repntThrd=null;
        dispose();
    }//GEN-LAST:event_btn_okActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Dialog_SystemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Dialog_SystemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Dialog_SystemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Dialog_SystemInfo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                Dialog_SystemInfo dialog = new Dialog_SystemInfo(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_ok;
    private javax.swing.JScrollPane jScrollPane1;
    private commanLib.Panel_CpuUsageBar panel_CpuUsageBar;
    private commanLib.Panel_RamUsageBar panel_RamUsageBar;
    private javax.swing.JTable table;
    // End of variables declaration//GEN-END:variables

class RepaintThread extends Thread
{
        public RepaintThread() 
        {
            start();
        }
        
        public void run()
        {
            while(true)
            {
                repaint();
                try {
                    Thread.sleep(200);
                } catch (InterruptedException ex) { }
            }
        }
    
}
    
}
