package commanLib.CATFeedback;

import java.awt.Toolkit;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

public class CATFeedback extends javax.swing.JFrame 
{   
    
    private int msgType = REPORT;
    
    public static final int REPORT=0;
    public static final int SUGGESTION=1;
    public static final int CONTACT=2;
    public static final int OTHERS=3;
    
    private Panel_ReportError panel_RptErr =null;
    private Panel_Suggstn panel_sugg = null;
    private Panel_Contact_Other panel_contact = null;
    private Panel_Contact_Other panel_other = null;
    
    public CATFeedback()
    {
        ConstructorBody();
    }
    
    public CATFeedback(int messageType,String prgmRespons,String prgmOutput)
    {     
        ConstructorBody();
        
        switch(messageType)
        {
            case REPORT : {
                               comboBx_msgType.setSelectedIndex(messageType);
                               comboBx_msgType.setEnabled(false);
                               panel_RptErr= new Panel_ReportError();
                               scrollPane_Message.setViewportView(panel_RptErr); 
                               panel_RptErr.setData(null, null, prgmRespons, prgmOutput, null);
                
                          }break;
        }
        
    }
        
    public void ConstructorBody() 
    {
        //(1)Set defualt look n feel
          try{
              //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
          }catch(Exception e)
          { 
              //System.out.println("Windows isn't available");               
          }
          
        initComponents();
        
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("/commanLib/images/gmailIcon.png")));
        
        this.setLocationRelativeTo(null); 
        
        panel_RptErr= new Panel_ReportError();
        scrollPane_Message.setViewportView(panel_RptErr);         
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl_banner = new javax.swing.JLabel();
        panel_genInfo = new javax.swing.JPanel();
        textF_email = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        textF_name = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        frmtdTextF_no = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        comboBx_msgType = new javax.swing.JComboBox();
        scrollPane_Message = new javax.swing.JScrollPane();
        btn_send = new javax.swing.JButton();
        btn_cancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("CAT FeedBack");
        setResizable(false);

        lbl_banner.setBackground(new java.awt.Color(255, 255, 255));
        lbl_banner.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl_banner.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/FeedBack_Bar.png"))); // NOI18N
        lbl_banner.setOpaque(true);

        panel_genInfo.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "General Information", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        textF_email.setToolTipText("Use Gmail Id only (e.g. abcde@gmail.com)");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/gmail.png"))); // NOI18N
        jLabel2.setText(" Your GMail email ID :");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/name.png"))); // NOI18N
        jLabel3.setText(" Full Name :");

        textF_name.setToolTipText("Your full name");

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/phone.png"))); // NOI18N
        jLabel4.setText(" Contact Number : ");

        frmtdTextF_no.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("###0"))));
        frmtdTextF_no.setToolTipText("Your contact number (Mobile/Phone etc)");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/commanLib/images/msgType.png"))); // NOI18N
        jLabel5.setText(" Message Type : ");

        comboBx_msgType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Report Error", "Suggestion", "Contact", "Other" }));
        comboBx_msgType.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                comboBx_msgTypeItemStateChanged(evt);
            }
        });

        javax.swing.GroupLayout panel_genInfoLayout = new javax.swing.GroupLayout(panel_genInfo);
        panel_genInfo.setLayout(panel_genInfoLayout);
        panel_genInfoLayout.setHorizontalGroup(
            panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(panel_genInfoLayout.createSequentialGroup()
                .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(panel_genInfoLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_genInfoLayout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textF_name))
                            .addGroup(panel_genInfoLayout.createSequentialGroup()
                                .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(panel_genInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(frmtdTextF_no, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(panel_genInfoLayout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textF_email, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(panel_genInfoLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBx_msgType, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        panel_genInfoLayout.setVerticalGroup(
            panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_genInfoLayout.createSequentialGroup()
                .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textF_email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textF_name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmtdTextF_no, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_genInfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(comboBx_msgType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        scrollPane_Message.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Message Body", javax.swing.border.TitledBorder.LEFT, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Tahoma", 0, 11), new java.awt.Color(0, 51, 255))); // NOI18N

        btn_send.setText("Send");
        btn_send.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_sendActionPerformed(evt);
            }
        });

        btn_cancel.setText("Close");
        btn_cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_cancelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lbl_banner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panel_genInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(scrollPane_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 530, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(layout.createSequentialGroup()
                .addGap(193, 193, 193)
                .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lbl_banner, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel_genInfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(scrollPane_Message, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_send, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btn_cancel, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 11, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_cancelActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_cancelActionPerformed

    private void comboBx_msgTypeItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_comboBx_msgTypeItemStateChanged
        // TODO add your handling code here:
        int choice = comboBx_msgType.getSelectedIndex();
        
        msgType=choice;
        switch(choice)
        {
            case 0 : {   //Report Error                             
                         panel_RptErr= new Panel_ReportError();
                         scrollPane_Message.setViewportView(panel_RptErr);                         
                     } break;
            case 1 : {   //Suggestions
                         panel_sugg= new Panel_Suggstn();
                         scrollPane_Message.setViewportView(panel_sugg);                         
                     } break;
            case 2 : {    //Contact
                         panel_contact= new Panel_Contact_Other();
                         scrollPane_Message.setViewportView(panel_contact);                         
                     } break;
            case 3 : {   //Others
                         panel_other= new Panel_Contact_Other();
                         scrollPane_Message.setViewportView(panel_other);                         
                     } break;
            default : msgType=-1; System.out.println("Invalid Selection"); break;
        }
    }//GEN-LAST:event_comboBx_msgTypeItemStateChanged

    private void btn_sendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_sendActionPerformed
        // TODO add your handling code here:        
        try
        {
           if(textF_email.getText().equals("") || textF_name.getText().equals("") || frmtdTextF_no.getText().equals("") )
           { throw new Exception("Incomplete Entry(s) !"); }
           
           String msgBody;
           if(msgType==CATFeedback.CONTACT || msgType==CATFeedback.OTHERS)
           {      msgBody=""; }
           else
           {
                  msgBody="Sender Information :\n"+
                          "______________________________________________________________\n"+           
                          "Email : "+textF_email.getText()+"\n"+
                          "Name : "+textF_name.getText()+"\n"+ 
                          "Contact Number : "+frmtdTextF_no.getText()+"\n"+
                          "______________________________________________________________\n\n";   
           }
           
           String subject=comboBx_msgType.getSelectedItem()+" - ";
           switch(msgType)
           {
            case 0 : {   //Report Error                             
                         msgBody+=panel_RptErr.getString();
                         subject+=panel_RptErr.getSubject();
                     } break;
            case 1 : {   //Suggestions
                         msgBody+=panel_sugg.getString();                       
                         subject+=panel_sugg.getSubject();
                     } break;
            case 2 : {    //Contact
                         msgBody+=panel_contact.getString();     
                         subject+=panel_contact.getSubject();
                     } break;
            case 3 : {   //Others
                         msgBody+=panel_other.getString();  
                         subject+=panel_other.getSubject();
                     } break;
            default : throw new Exception("Invalid Selection!"); 
           } 
           
           if(msgType==CATFeedback.CONTACT || msgType==CATFeedback.OTHERS)
           {      msgBody+="\n\nSender Information :\n"+                                           
                          "Name : "+textF_name.getText()+"\n"+ 
                          "Contact Number : "+frmtdTextF_no.getText()+"\n";
           }
           else
           { msgBody+="\n______________________________________________________________\n";   }
           //System.out.println(msgBody);                      
           
           Dialog_SendMail d = new Dialog_SendMail(this,true, msgType,textF_email.getText(), subject,msgBody);
           d.setVisible(true);
           
        }catch(Exception e)
        { 
            JOptionPane.showMessageDialog(this, "Please Complete all entries!", "Incomplete entry(s)", JOptionPane.WARNING_MESSAGE);
            //e.printStackTrace();
        }
    }//GEN-LAST:event_btn_sendActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CATFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CATFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CATFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CATFeedback.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CATFeedback().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_cancel;
    private javax.swing.JButton btn_send;
    private javax.swing.JComboBox comboBx_msgType;
    private javax.swing.JFormattedTextField frmtdTextF_no;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbl_banner;
    private javax.swing.JPanel panel_genInfo;
    private javax.swing.JScrollPane scrollPane_Message;
    private javax.swing.JTextField textF_email;
    private javax.swing.JTextField textF_name;
    // End of variables declaration//GEN-END:variables
}
