package commanLib.CATFeedback;

public class Panel_Suggstn extends javax.swing.JPanel 
{

    public Panel_Suggstn() {
        initComponents();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        textF_areaOfCrn = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textA_sugg = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        slider_rate = new javax.swing.JSlider();
        frmtdTextF_Rate = new javax.swing.JFormattedTextField();

        setPreferredSize(new java.awt.Dimension(500, 274));

        jLabel2.setText("Area of Concern :");

        jLabel3.setText("Rate (0-10) current state of your Area of Concern :");

        textA_sugg.setColumns(20);
        textA_sugg.setFont(new java.awt.Font("SansSerif", 0, 12)); // NOI18N
        textA_sugg.setLineWrap(true);
        textA_sugg.setRows(5);
        textA_sugg.setWrapStyleWord(true);
        jScrollPane2.setViewportView(textA_sugg);

        jLabel6.setText("Suggestions :");

        slider_rate.setMajorTickSpacing(1);
        slider_rate.setMaximum(10);
        slider_rate.setMinorTickSpacing(1);
        slider_rate.setPaintLabels(true);
        slider_rate.setPaintTicks(true);
        slider_rate.setSnapToTicks(true);
        slider_rate.setValue(5);
        slider_rate.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                slider_rateStateChanged(evt);
            }
        });

        frmtdTextF_Rate.setEditable(false);
        frmtdTextF_Rate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("##0"))));
        frmtdTextF_Rate.setText("5");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane2))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(frmtdTextF_Rate, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(textF_areaOfCrn, javax.swing.GroupLayout.DEFAULT_SIZE, 360, Short.MAX_VALUE)))
                                .addGap(22, 22, 22)))
                        .addContainerGap())
                    .addComponent(jSeparator2)))
            .addGroup(layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addComponent(slider_rate, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
                .addGap(38, 38, 38))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textF_areaOfCrn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 6, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(frmtdTextF_Rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(slider_rate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 5, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 108, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 128, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void slider_rateStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_slider_rateStateChanged
        // TODO add your handling code here:
        frmtdTextF_Rate.setText(String.valueOf(slider_rate.getValue()));
    }//GEN-LAST:event_slider_rateStateChanged

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JFormattedTextField frmtdTextF_Rate;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSlider slider_rate;
    private javax.swing.JTextArea textA_sugg;
    private javax.swing.JTextField textF_areaOfCrn;
    // End of variables declaration//GEN-END:variables

    public String getSubject() throws Exception
    {
        if(textF_areaOfCrn.getText().equals("") )
        { throw new Exception("Invalid Area of Concern!"); }
        else
        { return textF_areaOfCrn.getText(); }
    }
    
    public String getString() throws Exception
    {
        //chk values
        if(textF_areaOfCrn.getText().equals("") || frmtdTextF_Rate.getText().equals("") || textA_sugg.getText().equals("") )
        { throw new Exception("Incomplete Entry(s) !"); }
        
        String ret="";
        ret+="Area of Concern : "+textF_areaOfCrn.getText()+"\n"+
             "Rating : "+frmtdTextF_Rate.getText()+"\n"+             
             "Your Suggestions : "+textA_sugg.getText();
        return ret;
    }
}
