package commanLib;

import java.awt.Color;
import java.awt.Graphics;
import java.util.HashMap;
import java.util.Map;
import java.util.TreeMap;
import javax.swing.JLabel;
import org.hyperic.sigar.Mem;
import org.hyperic.sigar.ProcMem;
import org.hyperic.sigar.Sigar;
import org.hyperic.sigar.SigarException;



public class Panel_RamUsageBar extends javax.swing.JPanel 
{
    private volatile int UsgValue=0;
    private RamSigarThread ramThread=null;
    
    public Panel_RamUsageBar() {
        initComponents();
        
        try{
            ramThread = new RamSigarThread();
        }catch(Exception e){}
    }
    
       
    protected void paintComponent(Graphics g) 
    {
        super.paintComponents(g);
        
        g.drawRect(20, 15, 95, 90);
        g.setColor(Color.BLACK);
        g.fillRect(20, 15, 95, 90);       
        
        g.setColor(new Color(100,96,0));
        g.fillRect(40, 20, 55, 70);   
        
        g.setColor(new Color(255,246,0));
        int x=(UsgValue*70)/100;
        g.fillRect(40, 20+70-x, 55, x);   
    }
    
    public void stopThread()
    {
        ramThread.stop();
        ramThread=null;
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(135, 115));

        lbl.setForeground(new java.awt.Color(255, 246, 0));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("_/_");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl, javax.swing.GroupLayout.DEFAULT_SIZE, 95, Short.MAX_VALUE)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables


class RamSigarThread extends Thread
{    
    private Sigar sigar = null;    
    private Map<String, Long> pageFoults;
    
    RamSigarThread() throws Exception
    {
        sigar = new Sigar();        
        start();        
    }
    
    public void run()
    {           
        while(true)
        {
            try
            {                
                Map<String, String> map2 = getMetric();                
                UsgValue=(int) (double) Double.valueOf(map2.get("UsedPercent"));
                
                String str=Sigar.formatSize(Long.valueOf(map2.get("Used")))+"/"+Sigar.formatSize(Long.valueOf(map2.get("Total")));
                                
                lbl.setText(str);
            
                Thread.sleep(1000);
            
            }catch(Exception e){}
        }
    }
    
    private Map<String, String> getMetric() throws SigarException 
    {
        Mem mem = sigar.getMem();
        return (Map<String, String>) mem.toMap();
    }    
    
}




}
