package Test.SystemProp;

import java.awt.Color;
import java.awt.Graphics;
import javax.swing.JLabel;
import org.hyperic.sigar.CpuPerc;
import org.hyperic.sigar.Sigar;
import org.hyperic.sigar.SigarException;


public class Panel_UsageBar extends javax.swing.JPanel 
{
    private volatile int UsgValue=0;
    
    public Panel_UsageBar() {
        initComponents();
        
        try{
            new CpuSigarThread();
        }catch(Exception e){}
    }
    
       
    protected void paintComponent(Graphics g) 
    {
        super.paintComponents(g);
        
        g.drawRect(20, 15, 95, 90);
        g.setColor(Color.BLACK);
        g.fillRect(20, 15, 95, 90);       
        
        g.setColor(new Color(0,100,0));
        g.fillRect(40, 20, 55, 70);   
        
        g.setColor(new Color(0,255,0));
        int x=(UsgValue*70)/100;
        g.fillRect(40, 20+70-x, 55, x);   
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lbl = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(135, 115));

        lbl.setForeground(new java.awt.Color(0, 255, 0));
        lbl.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lbl.setText("0 %");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addComponent(lbl, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lbl;
    // End of variables declaration//GEN-END:variables


class CpuSigarThread extends Thread
{
    
    Sigar session = null;
    CpuPerc cpuPerc = null;
    double freeCpu = 0;
    
    CpuSigarThread() throws Exception
    {
        session = new Sigar();        
        start();        
    }
    
    public void run()
    {
        while(true)
        {
            try {
                  session = new Sigar();
                  cpuPerc = session.getCpuPerc();
                  freeCpu = cpuPerc.getIdle()*100;
                  UsgValue=(int)(100-freeCpu);
                  lbl.setText(UsgValue+" %");    
                  repaint();
            }catch (SigarException e)
            { }             
        }
                      
        
    }
    
}




}
